name: Zap Baseline

on:
  workflow_dispatch:

jobs:
  baseline-scan:
    name: OWASP Zap Baseline Scan
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'https://sveltekit-security-headers.vercel.app/'
          cmd_options: '-a -I'
